### ISSUE TITLE
Use rust-beanstalkd for distribution?

### ISSUE THREAD

**Issue by jack-michaud** [treyzania/fearlesschat#1]
https://github.com/schickling/rust-beanstalkd

**Comment by treyzania** [comment]
It's supposed to be a trustless system such that anyone who wants to run a router just can run `fearlessd --daemon 1234` (or start a systemd service or whatever you want) and it'll register itself into the DHT via random nodes it has in the cache (/var/cache/fearlesschat).  Beanstalkd seems to be more for centralized systems.

**Comment by jack-michaud** [comment]
You're absolutely right – I initially misunderstood the point of this project. Thanks for clearing this up for me!
